[[constraint]]
  name = "github.com/olivere/elastic"
  version = "6.2.8"
[[constraint]]
  branch = "master"
  name = "github.com/zalando/go-keyring"
[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
[[constraint]]
  branch = "master"
  name = "golang.org/x/net"
[prune]
  go-tests = true
  unused-packages = true 
